spring:
  profiles:
    active: dev
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #format_sql: true
        #use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://3.37.229.116:3307/bbldb
    username: bbl
    password: bbl12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  urldata:
    api: api
#mybatis:
 # type-aliases-package:
 # mapper-locations: classpath*:mapper/**/*.xml
  #configuration:
   # lazy-loading-enabled: true
    #aggressive-lazy-loading: false
    #map-underscore-to-camel-case: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

