spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        #format_sql: true
        #use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mysql://localhost:3306/testdb?rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  urldata:
    api: api

server:
  port: 8082
#mybatis:
 # type-aliases-package:
 # mapper-locations: classpath*:mapper/**/*.xml
  #configuration:
   # lazy-loading-enabled: true
    #aggressive-lazy-loading: false
    #map-underscore-to-camel-case: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

etc:
  data:
#    file: C:\Users\mrsbok\Downloads/test
    file: ./file